name: gen_art_bg
description: "Flutter Animated Generative Art Backgrounds collection. Can be used as a background or separately."
version: 0.3.11
homepage: https://github.com/khlebobul/gen_art_bg

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0